spring.application.name=school-management-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sms_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Colombo&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:12345678}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.sql.init.mode=never

app.jwt.secret=${JWT_SECRET:iTNEw2qQZ2d2Hqeu9C/BHQ7NP116jgfalSEHRTPEIC0=}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
app.documents.storage-dir=${DOCUMENT_STORAGE_DIR:uploads/documents}

springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-produces-media-type=application/json

server.error.include-message=never
